In [1]:
import numpy as np

In [2]:
a = np.eye(3)		 # 배열을 대각선으로 1 값으로 초기화
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
arr = np.array(range(20)).reshape((4,5)) # 배열을 1 부터 20 값으로 초기화
print(arr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
from bs4 import BeautifulSoup

In [5]:
html = '''<!DOCTYPE html><html><head><title>The kim's story</title></head><body><p class="title"><b>The kim's story</b></p><p class="story">    Once upon a time there were three little sisters; and their names were    <a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,    <a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and    <a href="http://example.com/tillie" class="sister brother" id="link3">Tillie</a>;    and they lived at the bottom of a well.</p></body></html>'''

In [6]:
soup = BeautifulSoup(html, 'html.parser')


In [7]:
import requests, bs4

In [8]:
resp = requests.get('https://www.naver.com')

In [9]:
#print(resp.text)
    

In [10]:
if (resp.status_code == requests.codes.ok):
    html = resp.text
#    print(html)

In [11]:
bs = bs4.BeautifulSoup(html, 'html.parser')
tags = bs.select('a.ah_a') # Top 뉴스
for t in tags :
    print(t.getText())


1
2018 kbs 연예대상


2
황광희


3
로또838회당첨번호


4
연예대상


5
광희


6
정찬우


7
팽현숙


8
바람과함께사라지다


9
거제 학교폭력


10
역모 반란의시대


11
손나은


12
위메프 반값특가


13
스카이캐슬 촬영지


14
다크타워 희망의탑


15
문가비


16
전참시


17
신이


18
김혜선


19
이수지


20
sky 캐슬 촬영지


1
2018 kbs 연예대상


2
황광희


3
로또838회당첨번호


4
연예대상


5
광희


6
정찬우


7
팽현숙


8
바람과함께사라지다


9
거제 학교폭력


10
역모 반란의시대


11
손나은


12
위메프 반값특가


13
스카이캐슬 촬영지


14
다크타워 희망의탑


15
문가비


16
전참시


17
신이


18
김혜선


19
이수지


20
sky 캐슬 촬영지



In [12]:
resp = requests.get('https://www.mediawiki.org/w/api.php?action=cirrus-settings-dump')

print(resp.text)